### PR TITLE
Reworking category annotation access to avoid issues with some JUnit …

### PR DESCRIPTION
**Pull request by JorgePCDV**
…extensions e.g. JUnitParams

### CODE REVIEW

**Comment by anuragkapur** [comment]
Hi @JorgePCDV please could you add some details around what problem you are trying to solve with this PR?

**Comment by JorgePCDV** [comment]
Hi Anurag,

We are trying to migrate our tests to Atam4j, and we currenlty use listeners to set test identifiers in thread local storage, which we use to improve logging and traceability of the requests that the acceptance tests make.

We tried to implement this using Rules, but for certain tests e.g. JUnitParams tests, this approach does not work. Therefore, our current best option is to use test listeners. 

Test listeners are a standard feature of JUnit and it seems like a useful addition to Atam4j.

**Comment by JorgePCDV** [comment]
In some cases Description.getMethodName() does not return a valid Java method name e.g. in a JUnitParams test. In this case, the exception was being caught but the Category annotation was not being successfully read.

**Comment by anuragkapur** [comment]
Thanks. Merging..

**Pull request merged**
