### PR TITLE
Refactoring the public interface

### PR DESCRIPTION
**Pull request by anuragkapur**
I was finding some of the classes like the manager, builder and initialiser a bit unintuitive and confusing. So suggesting the following changes:

* Refactor builder and manager …
    * Combined `AcceptanceTestsHealthCheckInitializer` and `AcceptanceTestHealthCheckManager` into the same class as the split seemed a bit arbitrary
    * Renamed the new combined class to `Atam4j` instead of `AcceptanceTestHealthCheckManager` as is does more than just managing the health-check (it also creates a test running schedule and actually schedule tests)
    * `AcceptanceTestsRunnerTaskSchedulerBuilder` was wrapped as a static inner class of `AcceptanceTestHealthCheckManager`. This seemed counter intuitive and confusing to me. I usually expect SomeClassBuilder to build SomeClass not SomeOtherClass. So refactored by renaming the `AcceptanceTestHealthCheckManager` (a relatively long class name to Atam4j
* Use sensible defaults for initialDelay and period of tests

### CODE REVIEW

**Comment by TJ-Cutajar** [comment]
+1

**Comment by anuragkapur** [comment]
Thanks @tjcutajar !
@phillbarber - Please review when you get a chance. I would like your views too before merging this.

**Comment by phillbarber** [comment]
Hi Anurag, really like your changes.  I agree with all of the points made.  The Builder was named badly.  Atam4J is a good name for the main public interface for the library.

Minor point... I did see that the Environment and AcceptanceTestState class was made static... I have submitted a minor change to make these instance variables, see what you think.  Wasn't quite happy about adding the getter to AcceptanceTestsRunnerTaskScheduler but preferred this over static variables.  

Cheers again mate, much appreciated

**Comment by phillbarber** [comment]
BTW... Feel free to merge if you like my additions.

**Comment by anuragkapur** [comment]
Thanks for the review @phillbarber 

Let me explain the reason behind the static variable for `AcceptanceTestsState`.. 

I did not want `AcceptanceTestsRunnerTaskScheduler` to __own__ the `AcceptanceTestsState`. Feels like `AcceptanceTestsRunnerTaskScheduler` should only be responsible for __scheduling tasks__ and nothing else. Owning and returning `AcceptanceTestsState` doesn't feel like a concern `AcceptanceTestsRunnerTaskScheduler` should handle. 

To achieve this (and prevent a leakage of concerns), `Atam4j` has to initialise it and it needs to be __static__ because it should be accessible to the static inner class (`Atam4jBuilder`).

So in summary, I think this boils down the following question:
__Who (i.e which class) owns `AcceptanceTestsState`?__     
If you think it is ok for `AcceptanceTestsRunnerTaskScheduler` to own it, then I am happy with commit https://github.com/atam4j/atam4j/commit/3153ee997ff487214c1ee443124ce3460f322fec. Else, we should reconsider the change.

Thoughts?

PS: I hinted the above thought process in my commit message: https://github.com/atam4j/atam4j/commit/0199d350d3e3f8f9aeacd95768c490162d94062c 
- There were only ever by 1 AcceptanceTestsState and Environment and hence it makes sense for these to be static. Additionally, making AcceptanceTestsState static facilitates accessing it in the build method without it being a variable in the builder
- AcceptanceTestsState is internal to Atam4j and hence should not be exposed via the builder

**Comment by phillbarber** [comment]
OK, understand your points Anurag and they make sense apart from one thing... AcceptanceTestsRunnerTaskScheduler did have an acceptanceTestState variable.

I have submitted another commit which is another alternative.  It involves injecting the AcceptanceTestState into the AcceptanceTestsRunnerTaskScheduler class when you call scheduleAcceptanceTestsRunnerTask()  

My reason for doing this is that I'd like to avoid static because I don't think it's absolutely necessary.  Each time I make something static I end up regretting it later down the line due to the inflexbility it brings with it.

Thoughts?  If you don't like the latest commit (if it looks weird/cluttered/wrong) then happy to go static... we could always come back to this.

Cheers

**Comment by anuragkapur** [comment]
This looks great. It achieves the design goal I was keen on (to ensure `AcceptanceTestsState` is not owned by `AcceptanceTestsRunnerTaskScheduler` and instead injected into it) without using a static variable.

Essentially, injecting it when invoking `scheduleAcceptanceTestsRunnerTask` method instead of the constructor, allows not having the variable declared static. 

I like it! Thanks! :+1: 

PS: `AcceptanceTestsRunnerTaskScheduler` did have an `acceptanceTestsState` instance variable, but it was private and no public getter method was exposing it.

**Pull request merged**
