### PR TITLE
Add stop method

### PR DESCRIPTION
**Pull request by tjcutajar**
Shuts down the scheduler.

### CODE REVIEW

**Comment by phillbarber** [comment]
Hi Tyrone, thanks for the PR. Looks good.
Just so i know,  what problem did this solve?
Thanks

**Comment by anuragkapur** [comment]
Question - do we really need code to do this? If someone wants the tests to not run, can they not simply stop the application?

I suppose this would be handy if the app running tests is also running something else. Is that what you had in mind @tjcutajar ?

**Comment by anuragkapur** [comment]
@tjcutajar - any thoughts on my previous question?

**Comment by phillbarber** [comment]
Hi @anuragkapur and @tjcutajar 
My vote would be to close and not merge this PR  unless we hear about what problem this is solving.  As you say @anuragkapur killing the application might be good enough at present.

Thanks

**Pull request closed without merging**
